usethis::create_package("dontology")
usethis::use_readme_md()
usethis::use_mit_license()
usethis::use_description()
usethis::use_testthat()
usethis::use_directory("inst")

usethis::use_pipe()
usethis::use_package("magrittr")
usethis::use_package("glue")
usethis::use_package("R6")
usethis::use_package("DBI")
usethis::use_package("RSQLite")
usethis::use_package("jsonlite")
usethis::use_package("knitr")
usethis::use_package("rmarkdown")
usethis::use_package("ggplot2")

usethis::use_r("Entity")
usethis::use_r("Ontology")
usethis::use_r("DocumentInstance")
usethis::use_r("structure_helpers")
usethis::use_r("init_db")
usethis::use_r("serialization")
usethis::use_r("predef_lab")
usethis::use_r("query")
usethis::use_r("export")


usethis::use_test("DocumentInstance")
usethis::use_test("Entity")
usethis::use_test("export")
usethis::use_test("init_db")
usethis::use_test("Ontology")
usethis::use_test("predef_lab")
usethis::use_test("query")
usethis::use_test("serialization")
usethis::use_test("structure_helpers")


covr::report()
lintr::lint_package()

usethis::use_vignette("intro")

